apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
spec:
  replicas: 3
  selector:
    app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: leo/webserver
          imagePullPolicy: Never
          ports:
            - containerPort: 80
