[package]
name = "ruts-wmi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.11.0"

[build.release]
strip = true
opt-level = "z"
lto = true