apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo running on minikube && sleep 36000"]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - name: busybox2
      image: busybox
      command: ["sh", "-c", "echo running on minikube && sleep 36000"]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  # 指定在minikube node上运行，后续ssh到这台机器查看
  nodeSelector:
    "kubernetes.io/hostname": minikube
  volumes:
    - name: cache-volume
      emptyDir: {}
